[package]
name = "ori-native-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
ori = { workspace = true }

taffy   = { workspace = true }
seahash = { workspace = true }
tracing = { workspace = true }

keyboard-types = { workspace = true }
