use ori_native_core::{Key, Modifiers, NamedKey};

pub fn convert_key(key: gdk4::Key) -> Key {
    // this is a patchwork solution generated by chatGPT

    Key::Named(match key {
        gdk4::Key::Return | gdk4::Key::KP_Enter => NamedKey::Enter,
        gdk4::Key::Escape => NamedKey::Escape,
        gdk4::Key::BackSpace => NamedKey::Backspace,
        gdk4::Key::Tab | gdk4::Key::ISO_Left_Tab => NamedKey::Tab,

        gdk4::Key::Left => NamedKey::ArrowLeft,
        gdk4::Key::Right => NamedKey::ArrowRight,
        gdk4::Key::Up => NamedKey::ArrowUp,
        gdk4::Key::Down => NamedKey::ArrowDown,
        gdk4::Key::Home => NamedKey::Home,
        gdk4::Key::End => NamedKey::End,
        gdk4::Key::Page_Up => NamedKey::PageUp,
        gdk4::Key::Page_Down => NamedKey::PageDown,

        gdk4::Key::Insert => NamedKey::Insert,
        gdk4::Key::Delete => NamedKey::Delete,
        gdk4::Key::Clear => NamedKey::Clear,

        gdk4::Key::Shift_L | gdk4::Key::Shift_R => NamedKey::Shift,
        gdk4::Key::Control_L | gdk4::Key::Control_R => NamedKey::Control,
        gdk4::Key::Alt_L | gdk4::Key::Alt_R => NamedKey::Alt,
        gdk4::Key::Meta_L | gdk4::Key::Meta_R => NamedKey::Meta,
        gdk4::Key::Super_L | gdk4::Key::Super_R | gdk4::Key::Hyper_L | gdk4::Key::Hyper_R => {
            NamedKey::Meta
        }
        gdk4::Key::Caps_Lock => NamedKey::CapsLock,
        gdk4::Key::Num_Lock => NamedKey::NumLock,
        gdk4::Key::Scroll_Lock => NamedKey::ScrollLock,

        gdk4::Key::F1 => NamedKey::F1,
        gdk4::Key::F2 => NamedKey::F2,
        gdk4::Key::F3 => NamedKey::F3,
        gdk4::Key::F4 => NamedKey::F4,
        gdk4::Key::F5 => NamedKey::F5,
        gdk4::Key::F6 => NamedKey::F6,
        gdk4::Key::F7 => NamedKey::F7,
        gdk4::Key::F8 => NamedKey::F8,
        gdk4::Key::F9 => NamedKey::F9,
        gdk4::Key::F10 => NamedKey::F10,
        gdk4::Key::F11 => NamedKey::F11,
        gdk4::Key::F12 => NamedKey::F12,
        gdk4::Key::F13 => NamedKey::F13,
        gdk4::Key::F14 => NamedKey::F14,
        gdk4::Key::F15 => NamedKey::F15,
        gdk4::Key::F16 => NamedKey::F16,
        gdk4::Key::F17 => NamedKey::F17,
        gdk4::Key::F18 => NamedKey::F18,
        gdk4::Key::F19 => NamedKey::F19,
        gdk4::Key::F20 => NamedKey::F20,
        gdk4::Key::F21 => NamedKey::F21,
        gdk4::Key::F22 => NamedKey::F22,
        gdk4::Key::F23 => NamedKey::F23,
        gdk4::Key::F24 => NamedKey::F24,

        gdk4::Key::KP_Insert => NamedKey::Insert,
        gdk4::Key::KP_Delete => NamedKey::Delete,
        gdk4::Key::KP_Home => NamedKey::Home,
        gdk4::Key::KP_End => NamedKey::End,
        gdk4::Key::KP_Page_Up => NamedKey::PageUp,
        gdk4::Key::KP_Page_Down => NamedKey::PageDown,
        gdk4::Key::KP_Left => NamedKey::ArrowLeft,
        gdk4::Key::KP_Right => NamedKey::ArrowRight,
        gdk4::Key::KP_Up => NamedKey::ArrowUp,
        gdk4::Key::KP_Down => NamedKey::ArrowDown,
        gdk4::Key::KP_Begin => NamedKey::Clear,

        gdk4::Key::Print => NamedKey::PrintScreen,
        gdk4::Key::Pause => NamedKey::Pause,
        gdk4::Key::Menu => NamedKey::ContextMenu,

        gdk4::Key::AudioPlay => NamedKey::MediaPlay,
        gdk4::Key::AudioPause => NamedKey::MediaPause,
        gdk4::Key::AudioStop => NamedKey::MediaStop,
        gdk4::Key::AudioNext => NamedKey::MediaTrackNext,
        gdk4::Key::AudioPrev => NamedKey::MediaTrackPrevious,
        gdk4::Key::AudioMute => NamedKey::AudioVolumeMute,
        gdk4::Key::AudioLowerVolume => NamedKey::AudioVolumeDown,
        gdk4::Key::AudioRaiseVolume => NamedKey::AudioVolumeUp,

        _ => match key.to_unicode() {
            Some(c) => return Key::Character(c.to_string()),
            None => NamedKey::Unidentified,
        },
    })
}

pub fn convert_modifiers(modifiers: gdk4::ModifierType) -> Modifiers {
    let mut mods = Modifiers::empty();

    if modifiers.contains(gdk4::ModifierType::SHIFT_MASK) {
        mods.insert(Modifiers::SHIFT);
    }

    if modifiers.contains(gdk4::ModifierType::CONTROL_MASK) {
        mods.insert(Modifiers::CONTROL);
    }

    if modifiers.contains(gdk4::ModifierType::META_MASK) {
        mods.insert(Modifiers::META);
    }

    if modifiers.contains(gdk4::ModifierType::ALT_MASK) {
        mods.insert(Modifiers::ALT);
    }

    mods
}
